" vim:fdm=marker
" TDOD's:
" - jump to last cursor position
" - mapping for moving up and down a few lines

" 1. PLUGINS {{{
" 1.1 Requirements {{{

set nocompatible

filetype off
filetype plugin indent off

" }}}
" 1.2 Instalation {{{

"execute 'source' '~/.vim/rc/dein.vimrc'

set runtimepath+=~/.vim/dein/repos/github.com/Shougo/dein.vim
if dein#load_state(expand('~/.vim/dein'))
    call dein#begin(expand('~/.vim/dein'))

    if !has('nvim') || v:version < 800
        call dein#add('Shougo/unite.vim')
        call dein#add('Shougo/vimproc.vim', { 'build': 'make' })
    else
        call dein#add('Shougo/denite.nvim')
    endif

    " LANGUAGE
    call dein#add('stanangeloff/php.vim')
    call dein#add('Shougo/neco-vim')
    call dein#add('shawncplus/phpcomplete.vim')
    call dein#add('fatih/vim-go')

    " COMPLETION
    call dein#add('ervandew/supertab')
    if has('nvim')
        call dein#add('Shougo/deoplete.nvim')
    else
        call dein#add('Shougo/neocomplete.vim')
    endif

    " NAVIGATION
    call dein#add('ctrlpvim/ctrlp.vim')
    call dein#add('scrooloose/nerdtree')
    call dein#add('eugen0329/vim-esearch')
    call dein#add('majutsushi/tagbar')
    call dein#add('mileszs/ack.vim')

    " LOOKS
    call dein#add('altercation/vim-colors-solarized')
    call dein#add('vim-airline/vim-airline')
    call dein#add('vim-airline/vim-airline-themes')

    " GIT
    call dein#add('airblade/vim-gitgutter')

    call dein#end()
    call dein#save_state()
endif

if dein#check_install()
    call dein#install()
endif
filetype plugin indent on
" }}}
" Customization {{{
" CtrlP {{{
if dein#tap('ctrlp.vim')
    let g:ctrlp_working_path_mode = 'ra'
    let g:ctrlp_show_hidden = 1
    let g:ctrlp_user_command = 'ag %s -i --nocolor --nogroup --hidden
          \ --ignore .git
          \ --ignore .svn
          \ --ignore .hg
          \ --ignore .DS_Store
          \ --ignore "**/*.pyc"
          \ -g ""'
    nnoremap <leader>p :CtrlP <CR>
endif
" }}}
" Airline {{{
if dein#tap('vim-airline')
    let g:airline#extensions#tabline#enabled = 1
    let g:airline#extensions#tabline#fnamemod = ':t'
    let g:airline_powerline_fonts = 1
    let g:airline_theme='solarized'
    let g:airline#extensions#tagbar#enabled = 1
endif
" }}}
" PHPComplete {{{
if dein#tap('phpcomplete.vim')
    au Filetype php setlocal ofu=phpcomplete#CompletePHP
endif
" }}}
" Deoplete {{{
if dein#tap('deoplete.nvim')
    let g:deoplete#enable_at_startup = 1
    let g:deoplete#omni_patterns = {}
    let g:deoplete#omni_patterns.php = '\h\w*\|[^. \t]->\%(\h\w*\)\?\|\h\w*::\%(\h\w*\)\?'
endif
" }}}
" Neocomplete {{{
if dein#tap('neocomplete.vim')
    let g:neocomplete#enable_at_startup = 1
    let g:neocomplete#omni_patterns = {}
    let g:neocomplete#omni_patterns.php = '\h\w*\|[^. \t]->\%(\h\w*\)\?\|\h\w*::\%(\h\w*\)\?'
endif
" }}}
" ESearch {{{
if dein#tap('vim-esearch')
    let g:esearch = {
      \ 'adapter':    'ack',
      \ 'backend':    'nvim',
      \ 'out':        'qflist',
      \ 'batch_size': 1000,
      \ 'use':        ['visual', 'hlsearch', 'last'],
      \}
    "call esearch#map('<leader>ff, 'esearch')
endif
" }}}
" Tagbar {{{
if dein#tap('tagbar')
    nnoremap <F8> :TagbarToggle<CR>
    let g:airline#extensions#tagbar#enabled = 1
endif
" }}}
" Ack {{{
if dein#tap('ack.vim')
    nnoremap <leader>a :Ack!<space>
endif
" }}}
" Vim-go {{{
if dein#tap('vim-go')
    au FileType go nmap <leader>r <Plug>(go-run)
    au FileType go nmap <leader>b <Plug>(go-build)
    au FileType go nmap <leader>t <Plug>(go-test)
    au FileType go nmap <leader>c <Plug>(go-coverage)

    if has('nvim')
        au Filetype go nmap <leader>rt <PLUG>(go-run-tab)
        au Filetype go nmap <leader>rs <PLUG>(go-run-split)
        au Filetype go nmap <leader>rv <PLUG>(go-run-vertical)
    endif
endif
" }}}
" }}}
" }}}
" 2. Looks {{{
" Use 256 colours
set t_Co=256 " TODO: move elsewhere

" only redraw when needed
set lazyredraw


" 2.1 Theme {{{

set background=dark
colorscheme solarized

set guifont=Hack:h9
set mouse=a
" }}}
" 2.2 Statusline {{{

" Always show statusline
set laststatus=2

" @see 1.3.2 Airline

" }}}
" 2.3 Code {{{

" show line number
set number
" show relative line numbers
set relativenumber

set cursorline
:hi CursorLine   cterm=NONE ctermbg=darkred ctermfg=white

" enable syntax highting
syntax on

" Tabs " TODO: move elsewhere?
set expandtab
set tabstop=4
set softtabstop=4
set shiftwidth=4

" Auto Indentation " TODO: move elsewhere?
set autoindent
set smartindent
set textwidth=80

"let php_folding = 1
"let javaScript_fold=1
" }}}
" }}}
" 3. Mappings {{{
" 3.1 General {{{

" Map Leader Key to Space
:let mapleader = "\<space>"


" Refresh .vimrc
nnoremap <leader>vr :so ~/.vimrc <CR>

" Open .vimrc
nnoremap <leader>vo :e  ~/.dotfiles/vim/.vim/rc/vimrc <CR>

" Toggle Highlight Search
noremap <leader>st :set invhlsearch<CR> " TODO: remap

" }}}
" 3.2 Movement {{{

" 3.2.1 Cursor {{{

" faster hjkl movement " TODO: make text objects ?
nnoremap <S-h> ^
nnoremap <S-J> 5j<CR>
nnoremap <S-k> 5k<CR>
nnoremap <S-l> $

" }}}

" 3.2.2 Text {{{

" Move Line Up/Down
nnoremap <A-j> :m .+1<CR>==
nnoremap <A-k> :m .-2<CR>==
inoremap <A-j> <Esc>:m .+1<CR>==gi
inoremap <A-k> <Esc>:m .-2<CR>==gi
vnoremap <A-j> :m '>+1<CR>gv=gv
vnoremap <A-k> :m '<-2<CR>gv=gv

" }}}

" }}}
" 3.3 Navigation {{{
" 3.3.1 Buffers {{{

" hide buffers when :e
" set hidden

nmap <leader>o :enew<CR>
nmap <leader>l :bnext<CR>
nmap <leader>h :bprevious<CR>
nmap <leader>q :bp <BAR> bd #<CR>
nmap <leader>bl :ls<CR>

" }}}
" 3.3.2 Window {{{

nnoremap <CR> <C-w>w

" }}}
" 3.3.3 Tab {{{

nnoremap <leader>tl :tabnext<CR>
nnoremap <leader>th :tabprevious<CR>
nnoremap <leader>to :tabedit<CR>
nnoremap <leader>tq :tabclose<CR>

" }}}
" }}}
" }}}
" 4. Misc {{{
" 4.1 Search {{{

" search as characters are entere
set incsearch
set grepprg=ack

" }}}
" Undo {{{
set noswapfile
set undodir=~/.vim/tmp/undo//
set undofile
set backupdir=~/.vim/tmp/backup//
set backup
" }}}
" }}}
