" vim:fdm=marker
" TDOD's:
" - jump to last cursor position
" - mapping for moving up and down a few lines

" 1. PLUGINS {{{
" 1.1 Requirements {{{

set nocompatible

filetype off
filetype plugin indent off

" }}}
" 1.2 Instalation {{{

"execute 'source' '~/.vim/rc/dein.vimrc'

set runtimepath+=~/.vim/dein/repos/github.com/Shougo/dein.vim
if dein#load_state(expand('~/.vim/dein'))
    call dein#begin(expand('~/.vim/dein'))

    " LANGUAGE
    call dein#add('stanangeloff/php.vim')
    call dein#add('Shougo/neco-vim')
    call dein#add('shawncplus/phpcomplete.vim')

    " COMPLETION
    call dein#add('ervandew/supertab')
    call dein#add('Shougo/deoplete.nvim')

    " NAVIGATION
    call dein#add('ctrlpvim/ctrlp.vim')
    call dein#add('scrooloose/nerdtree')
    "call dein#add('eugen0329/vim-esearch')
    call dein#add('majutsushi/tagbar')

    " LOOKS
    call dein#add('altercation/vim-colors-solarized')
    call dein#add('vim-airline/vim-airline')
    call dein#add('vim-airline/vim-airline-themes')

    " GIT
    call dein#add('airblade/vim-gitgutter')

    call dein#end()
    call dein#save_state()
endif

if dein#check_install()
    call dein#install()
endif
filetype plugin indent on
" }}}
" Customization {{{
" CtrP {{{
if dein#tap('ctrlp.vim')
    let g:ctrlp_working_path_mode = 'ra'
    let g:ctrlp_show_hidden = 1
    nnoremap <leader>p :CtrlP <CR>
endif
" }}}
" Airline {{{
if dein#tap('vim-airline')
    let g:airline#extensions#tabline#enabled = 1
    let g:airline#extensions#tabline#fnamemod = ':t'
    let g:airline_powerline_fonts = 1
    let g:airline_theme='solarized'
endif
" }}}
" PHPComplete {{{
if dein#tap('phpcomplete.vim')
    au Filetype php setlocal ofu=phpcomplete#CompletePHP
endif
" }}}
" Deoplete {{{
let g:deoplete#enable_at_startup = 1
let g:deoplete#omni_patterns = {}
let g:deoplete#omni_patterns.php = '\h\w*\|[^. \t]->\%(\h\w*\)\?\|\h\w*::\%(\h\w*\)\?'
" }}}
" ESearch {{{
if dein#tap('vim-esearch')
    let g:esearch = {
      \ 'adapter':    'ack',
      \ 'backend':    'nvim',
      \ 'out':        'win',
      \ 'batch_size': 1000,
      \ 'use':        ['visual', 'hlsearch', 'last'],
      \}
    "call esearch#map('<leader>ff, 'esearch')
endif
" }}}
" Tagbar {{{
nnoremap <F8> :TagbarToggle<CR>
" }}}
" }}}
" 2. Looks {{{
" Use 256 colours
set t_Co=256 " TODO: move elsewhere

" only redraw when needed
set lazyredraw


" 2.1 Theme {{{

set background=dark
colorscheme solarized

set guifont=Hack:h9

" }}}
" 2.2 Statusline {{{

" Always show statusline
set laststatus=2

" @see 1.3.2 Airline

" }}}
" 2.3 Code {{{

" show line number
set number
" show relative line numbers
set relativenumber

set cursorline
:hi CursorLine   cterm=NONE ctermbg=darkred ctermfg=white

" enable syntax highting
syntax on

" Tabs " TODO: move elsewhere?
set expandtab
set tabstop=4
set softtabstop=4
set shiftwidth=4

" Auto Indentation " TODO: move elsewhere?
set autoindent
set smartindent
set textwidth=80

let php_folding = 1
let javaScript_fold=1   
" }}}
" }}}
" 3. Mappings {{{
" 3.1 General {{{

" Map Leader Key to Space
:let mapleader = "\<space>"


" Refresh .vimrc
nnoremap <leader>vr :so ~/.vimrc <CR>

" Open .vimrc
nnoremap <leader>vo :e  ~/.dotfiles/vim/.vim/rc/vimrc <CR>

" Toggle Highlight Search
noremap <leader>st :set invhlsearch<CR> " TODO: remap

" }}}
" 3.2 Movement {{{

" 3.2.1 Cursor {{{

" Move in Insert Mode
imap <C-h> <C-o>h
imap <C-j> <C-o>j
imap <C-k> <C-o>k
imap <C-l> <C-o>l

" faster hjkl movement " TODO: make text objects ?
nnoremap <S-h> ^
nnoremap <S-J> G
nnoremap <S-k> gg
nnoremap <S-l> $

" }}}

" 3.2.2 Text {{{

" Move Line Up/Down
nnoremap <A-j> :m .+1<CR>==
nnoremap <A-k> :m .-2<CR>==
inoremap <A-j> <Esc>:m .+1<CR>==gi
inoremap <A-k> <Esc>:m .-2<CR>==gi
vnoremap <A-j> :m '>+1<CR>gv=gv
vnoremap <A-k> :m '<-2<CR>gv=gv

" }}}

" }}}
" 3.3 Navigation {{{

" 3.3.1 Buffers {{{

" hide buffers when :e
" set hidden

nmap <leader>o :enew<CR>
nmap <leader>l :bnext<CR>
nmap <leader>h :bprevious<CR>
nmap <leader>q :bp <BAR> bd #<CR>
nmap <leader>bl :ls<CR>

" }}}

" 3.3.2 Window {{{

" TODO: remap window movement

" }}}

" 3.3.3 Tab {{{

nnoremap <leader>tl :tabnext<CR>
nnoremap <leader>th :tabprevious<CR>
nnoremap <leader>to :tabedit<CR>
nnoremap <leader>tq :tabclose<CR>

" }}}

" }}}
" }}}
" 4. Misc {{{
" 4.1 Search {{{

" search as characters are entere
set incsearch

" }}}
" Undo {{{
set noswapfile
set undodir=~/.vim/tmp/undo//
set undofile
set backupdir=~/.vim/tmp/backup//
set backup
" }}}
" }}}
