"vim:fdm=marker

" 1. PLUGINS {{{
" 1.1 Requirements {{{

set nocompatible

filetype off
filetype plugin indent off

" }}}
" Instalation {{{

set runtimepath+=~/.vim/dein/repos/github.com/Shougo/dein.vim
if dein#load_state(expand('~/.vim/dein'))
    call dein#begin(expand('~/.vim/dein'))

    if !has('nvim') || v:version < 800
        call dein#add('Shougo/unite.vim')
        call dein#add('Shougo/vimproc.vim', { 'build': 'make' })
    else
        call dein#add('Shougo/denite.nvim')
    endif

    " LANGUAGE
    call dein#add('Shougo/neco-vim',                { 'on_ft': 'vim' })
    call dein#add('shawncplus/phpcomplete.vim',     { 'on_ft': 'php' })
    call dein#add('StanAngeloff/php.vim',           { 'on_ft': 'php' })
    call dein#add('rayburgemeestre/phpfolding.vim', { 'on_ft': 'php' })
    call dein#add('fatih/vim-go',                   { 'on_ft': 'go' })
    call dein#add('rhysd/vim-clang-format',         { 'on_ft': 'cpp' })
    call dein#add('tweekmonster/deoplete-clang2',   { 'on_ft': 'cpp' })

    " COMPLETION
    call dein#add('ervandew/supertab')
    if has('nvim')
        call dein#add('Shougo/deoplete.nvim',       { 'hook_add': 'source ~/.config/vim/plugins/deoplete.vim'})
    else
        call dein#add('Shougo/neocomplete.vim',     { 'hook_add': 'source ~/.config/vim/plugins/neocomplete.vim' })
    endif

    " NAVIGATION
    call dein#add('airblade/vim-rooter')
    call dein#add('ctrlpvim/ctrlp.vim',             { 'hook_source': 'source ~/.config/vim/plugins/ctrlp.vim' })
    call dein#add('voronkovich/ctrlp-nerdtree.vim')
    call dein#add('scrooloose/nerdtree',            { 'hook_source': 'source ~/.config/vim/plugins/nerdtree.vim' })
    call dein#add('majutsushi/tagbar')
    call dein#add('mileszs/ack.vim')

    " LOOKS
    call dein#add('altercation/vim-colors-solarized')
    call dein#add('vim-airline/vim-airline',        { 'hook_add': 'source ~/.config/vim/plugins/airline.vim' })
    call dein#add('vim-airline/vim-airline-themes')

    " GIT
    call dein#add('airblade/vim-gitgutter')
    call dein#add('tpope/vim-fugitive')

    " MISC
    call dein#add('benizi/vim-automkdir')
    call dein#add('neomake/neomake',                { 'hook_source': 'source ~/.config/vim/plugins/neomake.vim' })

    call dein#end()
    call dein#save_state()
endif

if dein#check_install()
    call dein#install()
endif
filetype plugin indent on
" }}}
" Customization {{{
" PHPComplete {{{
if dein#tap('phpcomplete.vim')
    au Filetype php setlocal ofu=phpcomplete#CompletePHP
endif
" }}}
" Tagbar {{{
if dein#tap('tagbar')
    nnoremap <F8> :TagbarToggle<CR>
    let g:airline#extensions#tagbar#enabled = 1
endif
" }}}
" Ack {{{
if dein#tap('ack.vim')
    nnoremap <leader>a :Ack!<space>
endif
" }}}
" GitGutter {{{
let g:gitgutter_map_keys = 0
" }}}
" Rooter {{{
let g:rooter_silent_chdir=1
" }}}
" }}}
" }}}
" 2. Looks {{{
" Use 256 colours
set t_Co=256 " TODO: move elsewhere

" only redraw when needed
set lazyredraw


" 2.1 Theme {{{

set background=dark
colorscheme solarized

set guifont=Hack:h9
set mouse=a
" }}}
" 2.2 Statusline {{{

" Always show statusline
set laststatus=2

" @see 1.3.2 Airline

" }}}
" 2.3 Code {{{

" show line number
set number
" show relative line numbers
set relativenumber

set cursorline
:hi CursorLine   cterm=NONE ctermbg=darkred ctermfg=white

" enable syntax highting
syntax on

" Tabs " TODO: move elsewhere?
set expandtab
set tabstop=4
set softtabstop=4
set shiftwidth=4

" Auto Indentation " TODO: move elsewhere?
set autoindent
set smartindent
set cindent
set textwidth=80

"let php_folding = 1
"let javaScript_fold=1
" }}}
" }}}
" 3. Mappings {{{
" 3.1 General {{{

" Map Leader Key to Space
let mapleader = "\<space>"

" Refresh .vimrc
nnoremap <leader>vr :so ~/.vimrc <CR>
" Open .vimrc
nnoremap <leader>vo :e  ~/.dotfiles/vim/.config/vim/vimrc<CR>

" Toggle Highlight Search
noremap <leader>st :set invhlsearch<CR> " TODO: remap

" }}}
" 3.2 Movement {{{
" 3.2.1 Cursor {{{

" faster hjkl movement " TODO: make text objects ?
nnoremap <S-h> ^
"nnoremap <S-J>5j<CR>
"vnoremap <S-k>5k<CR>
nnoremap <S-l> $

" }}}
" 3.2.2 Text {{{

" Move Line Up/Down
nnoremap <A-j> :m .+1<CR>==
nnoremap <A-k> :m .-2<CR>==
inoremap <A-j> <Esc>:m .+1<CR>==gi
inoremap <A-k> <Esc>:m .-2<CR>==gi
vnoremap <A-j> :m '>+1<CR>gv=gv
vnoremap <A-k> :m '<-2<CR>gv=gv

" }}}
" }}}
" 3.3 Navigation {{{
" 3.3.1 Buffers {{{

" hide buffers when :e
" set hidden

noremap <leader>o :enew<CR>
noremap <silent><leader>l :bnext<CR>
noremap <silent><leader>h :bprev<CR>
noremap <leader>q :bp <BAR> bd #<CR>
noremap <leader>bl :ls<CR>

" }}}
" 3.3.2 Window {{{

nnoremap <CR> <C-w>w

" }}}
" 3.3.3 Tab {{{

nnoremap <leader>tl :tabnext<CR>
nnoremap <leader>th :tabprevious<CR>
nnoremap <leader>to :tabedit<CR>
nnoremap <leader>tq :tabclose<CR>

" }}}
" }}}
" }}}
" 4. Misc {{{
" 4.1 Search {{{

" search as characters are entere
set incsearch
set grepprg=ack

" }}}
" Undo {{{
set noswapfile
set undodir=~/.vim/tmp/undo//
set undofile
set backupdir=~/.vim/tmp/backup//
set backup
" }}}
" }}}
" Functions {{{
function! ClearCache()
    :! rm -rf ~/.vim/dein/.cache/*
    call dein#update()
    source ~/.vimrc
endfunction
" }}}
